[[https://img.shields.io/badge/hugo-0.72-blue.svg]]
[[https://github.com/bphenriques/knowledge-base/workflows/Build%20&%20Deploy/badge.svg?event=push]]
[[https://img.shields.io/badge/License-MIT-blue.svg]]

* Knowledge Base

Source code of my personal wiki available at [[https://bphenriques.github.io/knowledge-base][bphenriques.github.io/knowledge-base]] using [[https://orgmode.org/][org-mode]] and [[https://ox-hugo.scripter.co/][ox-hugo.]]

* How it works

The content is written in the ~org-mode~ format in the ~org~ directory where:
- Each subdirectory under ~org/docs~ represents a section (a [[https://gohugo.io/content-management/page-bundles/][Hugo page bundle]]).
- Each ~*.org~ file within represents an entry.
- Each ~_index.org~ file contains mostly setup information which eases migrating entries between folders.

For example:
#+BEGIN_SRC
.
├── _index.org
└── docs
    ├── _index.org
    ├── assorted-note.org
    ├── first-section
    │   ├── _index.org
    │   └── entry.org
    └── second-section
        ├── _index.org
        └── entry.org
#+END_SRC

Then, ~build.el~ acts as the key component to automate transforming the ~*.org~ files to their ~*.md~ counterpart using ox-hugo, which in turn feeds ~gohugo~ to generate the final version of the website. Builds happen on the ~gh-pages~ branch (using [[https://git-scm.com/docs/git-worktree][git-worktree]] and [[https://git-scm.com/docs/git-checkout/#Documentation/git-checkout.txt---orphanltnewbranchgt][orphan branches]]).

** Org Capture

In the root of the project you will find two ~org-capture~ templates that I personally use. Feel free to contact me for the dotfiles while they are not available.

* Run locally

1. Export existing ~*.org~ content and run the website locally:
   #+BEGIN_SRC bash
   $ make clean build-content serve
   #+END_SRC
2. Open [[http://localhost:1313][localhost:1313]].

* Contributing

Feel free to send feedback! I look forward to include your insights on my notes :)

* Reference

- [[https://gohugo.io/][Hugo Static Page Generator]]
- [[https://github.com/alex-shpak/hugo-book][Hugo Book Theme]]
- [[https://ox-hugo.scripter.co/][Ox-Hugo]]

* Inspired by

There are several personal Wikis made by other people that inspired me to make one for me. Follows some notable examples:
- [[https://github.com/jethrokuan/braindump]]
- [[https://wiki.nikitavoloboev.xyz]]
- https://beepb00p.xyz/exobrain/exobrain.html
- http://okmij.org/ftp/
- https://notes.andymatuschak.org/About_these_notes
