[[https://img.shields.io/badge/hugo-0.85.0-blue.svg]]
[[https://github.com/bphenriques/knowledge-base/workflows/Build%20&%20Deploy/badge.svg?event=push]]
[[https://img.shields.io/badge/License-MIT-blue.svg]]

* Digital Garden

My digital garden is available at [[https://bphenriques.github.io/knowledge-base][bphenriques.github.io/knowledge-base]].

* How it works

The content is written using ~org-mode~ in the ~org~ directory where each ~*.org~ file is a new note.

Then, using [[https://ox-hugo.scripter.co/][ox-hugo]], each ~*.org~ file is converted to ~*.md~ which will feed ~gohugo~ to generate my digital garden.

* Run locally

1. Export existing ~*.org~ content and run the website locally:
   #+BEGIN_SRC bash
   $ make clean build-content serve
   #+END_SRC
2. Open [[http://localhost:1313][localhost:1313]].

* Contributing

Feel free to send feedback! I look forward to include your insights on my notes :)

* Reference

- [[https://gohugo.io/][Hugo Static Page Generator]]
- [[https://github.com/alex-shpak/hugo-book][Hugo Book Theme]]
- [[https://ox-hugo.scripter.co/][Ox-Hugo]]

* Inspired by

There are several personal Wikis made by other people that inspired me to make one for me. Follows some notable examples:
- [[https://github.com/jethrokuan/braindump]]
- [[https://wiki.nikitavoloboev.xyz]]
- https://github.com/maggiedelano/digital-garden/
- https://beepb00p.xyz/exobrain/
- http://okmij.org/ftp/
- https://notes.andymatuschak.org/About_these_notes
- http://okmij.org/ftp/
- https://notes.aravindballa.com/

* Theme

The theme is [[https://github.com/bphenriques/tagged-notes-hugo-theme][Tagged Digital Garden]], a theme heavily based on [[https://github.com/alex-shpak/hugo-book][Hugo Book Theme]] with a twist of [[https://github.com/mrmartineau/gatsby-theme-code-notes][Gatsby Theme Code Nodes]] and [[https://www.maggiedelano.com/garden/][Maggie Delano's digital garden]].

I am no front-end expert so I look forward for your help improving the theme if you like it!
