name = "Tagged Notes"
license = "MIT"
licenselink = "https://github.com/bphenriques/knowledge-base/blob/master/LICENSE"
description = "Hugo digital garden theme with tag navigation"
homepage = "https://github.com/bphenriques/knowledge-base"
tags = ["responsive", "clean", "digital-garden", "docs", "flexbox", "search", "mobile"]
features = []
min_version = "0.68"

[author]
  name = "Bruno Henriques"
  homepage = "https://github.com/bphenriques/"
