name: Deploy Github Pages on gh-pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.69.2"
          extended: true

      - name: Build
        run: hugo --minify --cleanDestinationDir --baseURL https://bphenriques.github.io/knowledge-base

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

